### ISSUE TITLE
Некорректный подсчёт рейтинга

### ISSUE THREAD

**Issue by snowlue** [thecattest/yandex-tools#10]
Вместе с @BUYT-1 (Алексеем) обнаружили, что рейтинг считается не совсем точно. Я протестил подсчёт на [вашем скрипте](github.com/thecattest/yandex-tools/blob/master/rating.py) и [скрипте Алексея](github.com/BUYT-1/yalyc-rating/blob/main/calculate_rating.py). Я не делал ревью вашего кода и кода Алексея, но становлюсь, так или иначе, связующим звеном между вами. Может быть стоит внести правки, как думаете?

По словам Алексея:
> В вашем скрипте забиты вручную формулы для первого курса, в моём скрипте по имеющимся данным пытается подобрать коэффициенты в формулу.

Прикрепляю скриншот: в первом случае ваш скрипт, во втором — скрипт Алексея.

![image](https://user-images.githubusercontent.com/22418658/108705785-cc2e7f00-751e-11eb-9c73-f85081cb9833.png)

**Comment by thecattest** [comment]
есть какая-то информация о том, какой вариант более точный? я уже закончил лицей и не имею возможности тестировать ни в каком виде, но я не против обновлять скрипт. на момент написания проекта не было точной информации о том, как вычислять рейтинг

**Comment by snowlue** [comment]
Как я выяснил, скрипт Алексея всё же точнее.

**Comment by mnedo** [comment]
Несколько дней назад Яндекс.Лицей исправлял ошибку в подсчете рейтинга. 
После этих изменений алгоритм @thecattest считает довольно точно.

**Comment by snowlue** [comment]
@Mnedo, смотря кого вы имеете в виду.

**Comment by thecattest** [comment]
ох, что-то я вообще забыл про этот issue

окей, оставляем значит мой скрипт, спасибо всем
