### ISSUE TITLE
No requests in requirements.txt

### ISSUE THREAD

**Issue by bogdan-nikitin** [thecattest/yandex-tools#4]
requests package is not specified in the requirements.txt

**Comment by thecattest** [comment]
> requests package is not specified in the requirements.txt

mb I'm missing something, but actually it is

**Comment by thecattest** [comment]
this package is the only specified
@bogdan-nikitin

**Comment by bogdan-nikitin** [comment]
Sorry, I just forgot to run `pip install -r requirements.txt`, so I thought you didn't specify this package
> извиняюсь, зря быканул

**Comment by thecattest** [comment]
no problem
