### ISSUE TITLE
count_not_solved_tasks.py вылетает при наличии уроков без дедлайна

### ISSUE THREAD

**Issue by Hi-Timofey** [thecattest/yandex-tools#7]
Скрипт **count_not_solved_tasks.py** будет вылетать при попытке обработать уроки без ограничений по времени на выполнение (Такие как _"работа с Git"_). Вызвано это тем, что такое уроки в поле **msBeforeDeadline** имеют значение **None**.

**Comment by thecattest** [comment]
Благодарю за исправление
