### ISSUE TITLE
New auth policy of Yandex breakes Authorization

### ISSUE THREAD

**Issue by Hi-Timofey** [thecattest/yandex-tools#9]
As I know,  new policy of Yandex **requires** to auth with telephone number and confirm entry via phone call. It means that function _auth_ in methods.py now can't work well and raise exception _"Ошибка X" :_
```

Traceback (most recent call last):
  File "/home/user/combat/python_workspace/yandex-tools/rating.py", line 8, in <module>
    s = get_and_auth()
  File "/home/user/combat/python_workspace/yandex-tools/methods.py", line 39, in get_and_auth
    auth(s, login, password)
  File "/home/user/combat/python_workspace/yandex-tools/methods.py", line 24, in auth
    raise Exception('Ошибка X')
Exception: Ошибка X

```
because of importance of the methods.py file that new policy brokes whole functionality of the project. 
Attached file is request output when I try to connect to yandex (got it from auth.txt variable in method _auth_ of methods.py). In file hidden phone number. In normal output it will show first 3 numbers and 2 last numbers.
[output_ya_tools.zip](https://github.com/thecattest/yandex-tools/files/5864312/output_ya_tools.zip)

**Comment by thecattest** [comment]
seems to me that this problem is connected to your personal account limits, as I can't generate same problem. mb you have turned on 2fa or something?

**Comment by Hi-Timofey** [comment]
> seems to me that this problem is connected to your personal account limits, as I can't generate same problem. mb you have turned on 2fa or something?

Okay, after 21 days I have won this issues by writing to support to disable 2fa in my account. That's was, now obviously, not trouble of the current project. Thank's, closing issue)
